

services:
  springboot-app:
    build:
      context: ./backend/HoteBooking
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/hotel
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
    environment:
      - REACT_APP_API_URL=http://springboot-app:8080
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hotel
    volumes:
      - mysql-data:/var/lib/mysql


volumes:
  mysql-data:
